version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
        # install npm
        - npm install
        - npm install -g typescript
  pre_build:
    commands:
      - npm run build     
  build:
    commands:
      # run build script
      - npm pack 
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`  
artifacts:
  # include all files required to run application
  # notably excluded is node_modules, as this will cause overwrite error on deploy
  files:
    - 'dist/**/*'
    - '*.tgz' 
