version: 0.2

phases:
 install:
    commands:
      - echo "Installing project dependencies..."
      - npm install
      - npm install --save-dev typescript    

 build:
    commands:
      - echo "Building project..."
      - npm run build
      - npm pack
      - echo "Build started on `date`"
artifacts:
 files:
    - 'dist/**/*'
    - '*.tgz' 
